<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'factory' => '/Factory.php',
                'hardquotesapplication' => '/HardQuotesApplication.php',
                'noquotefoundexception' => '/quotes/NoQuoteFoundException.php',
                'quote' => '/quotes/Quote.php',
                'quotecollection' => '/quotes/QuoteCollection.php',
                'quoteline' => '/quotes/QuoteLine.php',
                'quotereader' => '/quotes/QuoteReader.php',
                'randomquotecommand' => '/commands/RandomQuoteCommand.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
